[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.build]
cmds = ["dotnet publish HotelReservation.Web/HotelReservation.Web.csproj -c Release -o out"]

[start]
cmd = "cd out && dotnet HotelReservation.Web.dll"
